/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import React from "react";
import { links } from "../utils/constants";
import Link from "next/link";
import CartButtons from "./CartButtons";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title ? title : "Zicomm2.0"}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-col w-full min-h-screen justify-between '>
        <header className=' '>
          <nav className='relative flex justify-between items-center h-20 w-11/12 mx-auto '>
            <div className='text-5xl'>
              <Link href='/'>
                <a className='pointer'>
                  <img src='/logo.svg' alt='Logo' width='175px' height='80px' />
                </a>
              </Link>
            </div>

            <ul className='flex  items-center gap-4 capitalize'>
              {links.map((link) => (
                <li key={link.id}>
                  <Link href={link.url}>
                    <a>{link.text}</a>
                  </Link>
                </li>
              ))}
            </ul>

            <CartButtons />
          </nav>
        </header>
        <main>{children}</main>
        <footer className='footer bg-[#222]'>
          <div>
            <p className='text-white'>
              &copy; 2022 Zicomm2.0 All rights reserved
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Layout;
